name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no github@18.143.164.250 << 'EOF'
          cd /opt/source/cg_quiz
          sudo git pull
          sudo docker stop cg_quiz_app
          sudo docker rm cg_quiz_app
          sudo docker image prune -a -f
          sudo docker --debug  build -t cg_quiz_app .
          sudo docker run --name cg_quiz_app -d --network=bridge -e "ENVIRONMENT=prod" -p 80:8080 cg_quiz_app
        EOF
